"""
Tier 3 — Session memory.

Holds the volatile, per-session conversation state: the last N turns raw
plus a rolling summary of everything older than that. Persists to a
per-session JSON file so restarting the server doesn't wipe context.

Design notes:

Hermes itself carries the full conversation state on the hermes-side
session (that's what Phase 1's --resume buys us). So what is Tier 3 for?

Three things hermes does NOT give us easily:
  1. A stable, OUR-SIDE record of each turn, with timestamps, for the
     mood classifier (Phase 3) and later content analysis.
  2. A rolling summary we can inject on turn 1 of a NEW session to
     "remember" prior sessions (today the agent is amnesiac across
     session boundaries unless we re-inject).
  3. Replayable state for debugging — if something goes sideways, we
     can see exactly what the character saw, in order.

The summary is generated by a cheap hermes call every SUMMARY_INTERVAL
turns, running in the background so it never blocks the user.

Part of: .hermes/plans/2026-04-17_personality-evolution.md (Phase 2a)
"""

from __future__ import annotations

import json
import time
from dataclasses import dataclass, field, asdict
from pathlib import Path
from typing import List, Optional, Dict, Any, Literal
from loguru import logger


# Tune-ables. Exposed as module constants so tests can monkeypatch.
MAX_RECENT_TURNS = 20       # keep this many raw turns in context
SUMMARY_INTERVAL = 10       # regenerate rolling summary every N turns
MAX_SUMMARY_CHARS = 2000    # cap on rolling summary size


Role = Literal["user", "assistant", "system"]


@dataclass
class Turn:
    """One conversation turn — who spoke, what was said, when."""

    role: Role
    content: str
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Turn":
        return cls(
            role=data["role"],
            content=data["content"],
            timestamp=float(data.get("timestamp", time.time())),
        )


@dataclass
class SessionMemory:
    """Tier 3 — volatile session state.

    Stores recent turns raw, compresses older ones into a rolling summary.
    Persists itself to a JSON file on disk so server restarts don't wipe
    state mid-conversation.
    """

    # Full list of turns ever added to this memory, in order. The list
    # can grow unbounded — we never prune from here; we just select a
    # window of the most recent for prompt injection.
    turns: List[Turn] = field(default_factory=list)

    # A rolling natural-language summary of everything before the most
    # recent MAX_RECENT_TURNS. Regenerated by summarize() every
    # SUMMARY_INTERVAL turns. May be empty (young sessions, or summary
    # hasn't been generated yet).
    rolling_summary: str = ""

    # Monotonically increasing counter of turns added since last summary.
    # Separate from len(turns) so we can trigger re-summarize on delta.
    turns_since_summary: int = 0

    # Optional path where this memory persists to. Set via
    # attach_file() or constructor. When None, save()/load() no-op.
    persist_path: Optional[Path] = None

    # --- Mutation ---

    def add_turn(self, role: Role, content: str) -> None:
        """Append a new turn. Does nothing if content is empty or a
        duplicate of the most recent turn (defensive against repeated
        calls from the agent layer).
        """
        content = content.strip()
        if not content:
            return
        if (
            self.turns
            and self.turns[-1].role == role
            and self.turns[-1].content == content
        ):
            return
        self.turns.append(Turn(role=role, content=content))
        self.turns_since_summary += 1
        self.save()

    # --- Window selection ---

    def recent(self, n: int = MAX_RECENT_TURNS) -> List[Turn]:
        """Return the last n turns, newest last. If fewer than n exist,
        returns all of them.
        """
        if n <= 0:
            return []
        return self.turns[-n:]

    def older_than_recent(self, n: int = MAX_RECENT_TURNS) -> List[Turn]:
        """Return turns OLDER than the recent window — the ones we
        should have summarized. Used by summarize() to build the
        summarization prompt.
        """
        if len(self.turns) <= n:
            return []
        return self.turns[:-n]

    # --- Summarization hook ---

    def needs_summary(self) -> bool:
        """True if enough new turns have accumulated to warrant a
        background summary refresh. Cheap to call every turn.
        """
        return (
            self.turns_since_summary >= SUMMARY_INTERVAL
            and len(self.turns) > MAX_RECENT_TURNS
        )

    def set_summary(self, new_summary: str) -> None:
        """Update the rolling summary from outside (the summarizer runs
        async; this is the callback). Resets the counter and persists.
        """
        new_summary = new_summary.strip()
        if len(new_summary) > MAX_SUMMARY_CHARS:
            new_summary = new_summary[: MAX_SUMMARY_CHARS - 3] + "..."
        self.rolling_summary = new_summary
        self.turns_since_summary = 0
        self.save()
        logger.info(
            f"SessionMemory summary updated: {len(new_summary)} chars "
            f"covering {len(self.older_than_recent())} older turns"
        )

    # --- Persistence ---

    def attach_file(self, path: Path) -> None:
        """Attach a persistence path. Future mutations save here."""
        self.persist_path = Path(path).expanduser()

    def save(self) -> None:
        """Atomically write state to persist_path (if set).

        Writes to a sibling .tmp file then renames, so a crash mid-write
        can never leave a truncated JSON file that would fail to load on
        next startup.
        """
        if self.persist_path is None:
            return
        self.persist_path.parent.mkdir(parents=True, exist_ok=True)
        tmp = self.persist_path.with_suffix(self.persist_path.suffix + ".tmp")
        payload = {
            "turns": [t.to_dict() for t in self.turns],
            "rolling_summary": self.rolling_summary,
            "turns_since_summary": self.turns_since_summary,
        }
        with tmp.open("w", encoding="utf-8") as f:
            json.dump(payload, f, ensure_ascii=False, indent=2)
        tmp.replace(self.persist_path)

    @classmethod
    def load(cls, path: Path) -> "SessionMemory":
        """Load from disk. Returns a fresh empty memory if the file
        doesn't exist. Raises on a malformed file so we never silently
        lose state.
        """
        path = Path(path).expanduser()
        if not path.is_file():
            logger.debug(f"No session memory at {path}, starting fresh")
            mem = cls()
            mem.attach_file(path)
            return mem
        with path.open("r", encoding="utf-8") as f:
            data = json.load(f)
        mem = cls(
            turns=[Turn.from_dict(t) for t in data.get("turns", [])],
            rolling_summary=str(data.get("rolling_summary", "")),
            turns_since_summary=int(data.get("turns_since_summary", 0)),
        )
        mem.attach_file(path)
        logger.info(
            f"SessionMemory loaded from {path}: "
            f"{len(mem.turns)} turns, summary={len(mem.rolling_summary)} chars"
        )
        return mem

    # --- Introspection (for composer) ---

    def render_recent(self, n: int = MAX_RECENT_TURNS) -> str:
        """Render the recent window as a `Role: content` block suitable
        for prompt injection. Returns empty string if no turns.
        """
        window = self.recent(n)
        if not window:
            return ""
        lines: List[str] = []
        for turn in window:
            role_display = turn.role.capitalize()
            lines.append(f"{role_display}: {turn.content}")
        return "\n".join(lines)

    def token_estimate_recent(self, n: int = MAX_RECENT_TURNS) -> int:
        """Rough token estimate of the recent window. 1 token ≈ 4 chars."""
        return (len(self.render_recent(n)) + 3) // 4

    def token_estimate_summary(self) -> int:
        return (len(self.rolling_summary) + 3) // 4


def build_summary_prompt(turns: List[Turn], prior_summary: str = "") -> str:
    """Build the prompt we send to hermes to regenerate the rolling summary.

    The summarizer runs asynchronously out-of-band from the user's turn.
    This function is pure (no side effects) and returns the prompt string;
    the actual summarization call lives in the agent layer.

    Strategy: give hermes the prior summary (if any) plus the turns that
    have happened since, and ask for a compressed "what has happened"
    paragraph. This is a classic rolling context window summarizer.
    """
    lines = [
        "You are compressing a long conversation into a short summary "
        "that will be shown to the same character on a future turn so "
        "they remember the context. Write 2-3 paragraphs, present tense, "
        "third-person. Capture: what the user seems to want, recurring "
        "themes, important factual details the character should retain, "
        "and the emotional arc. Do NOT quote messages verbatim.",
        "",
    ]
    if prior_summary.strip():
        lines.append("Prior summary of even older turns:")
        lines.append(prior_summary.strip())
        lines.append("")
        lines.append("Since then, the conversation went:")
    else:
        lines.append("The conversation so far:")

    for turn in turns:
        role = turn.role.capitalize()
        lines.append(f"{role}: {turn.content}")

    lines.append("")
    lines.append("Summary:")
    return "\n".join(lines)
